-- ============================================================================
-- BLOCKER PATCH (generated by db-blocker-audit.mjs --fix)
-- ============================================================================
-- NOTE: This patch ONLY adds missing columns and stub functions.
--       It does NOT create indexes/constraints/triggers/views/policies.
-- ============================================================================

DO $$
BEGIN
  IF to_regclass('public.documents') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS ai_last_run_status text';
  END IF;

  IF to_regclass('public.documents') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS ai_expiration_date date';
  END IF;

  IF to_regclass('public.documents') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS related_cost_id uuid';
  END IF;

  IF to_regclass('public.documents') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS related_invoice_id uuid';
  END IF;

  IF to_regclass('public.documents') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS is_archived boolean';
  END IF;

  IF to_regclass('public.documents') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS version_group_id uuid';
  END IF;

  IF to_regclass('public.subs') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.subs ADD COLUMN IF NOT EXISTS compliance_license_expiration text';
  END IF;

  IF to_regclass('public.subs') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.subs ADD COLUMN IF NOT EXISTS total_cost numeric';
  END IF;

  IF to_regclass('public.subs') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.subs ADD COLUMN IF NOT EXISTS project_id uuid';
  END IF;

  IF to_regclass('public.proposals') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.proposals ADD COLUMN IF NOT EXISTS public_token text';
  END IF;

  IF to_regclass('public.material_receipts') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.material_receipts ADD COLUMN IF NOT EXISTS receipt_date date';
  END IF;

  IF to_regclass('public.material_receipts') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.material_receipts ADD COLUMN IF NOT EXISTS linked_cost_id uuid';
  END IF;

  IF to_regclass('public.labor_pay_runs') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.labor_pay_runs ADD COLUMN IF NOT EXISTS payment_date date';
  END IF;

  IF to_regclass('public.labor_pay_runs') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.labor_pay_runs ADD COLUMN IF NOT EXISTS company_id uuid';
  END IF;

  IF to_regclass('public.project_budget_lines') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.project_budget_lines ADD COLUMN IF NOT EXISTS group_id uuid';
  END IF;

  IF to_regclass('public.project_budget_lines') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.project_budget_lines ADD COLUMN IF NOT EXISTS sort_order integer';
  END IF;

  IF to_regclass('public.scope_block_cost_items') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.scope_block_cost_items ADD COLUMN IF NOT EXISTS breakdown_notes text';
  END IF;

  IF to_regclass('public.checklist_template_items') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.checklist_template_items ADD COLUMN IF NOT EXISTS checklist_template_id uuid';
  END IF;

  IF to_regclass('public.measurement_units') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.measurement_units ADD COLUMN IF NOT EXISTS code text';
  END IF;

  IF to_regclass('public.measurement_units') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.measurement_units ADD COLUMN IF NOT EXISTS company_id uuid';
  END IF;

  IF to_regclass('public.project_budget_groups') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.project_budget_groups ADD COLUMN IF NOT EXISTS project_id uuid';
  END IF;

  IF to_regclass('public.proposal_settings') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.proposal_settings ADD COLUMN IF NOT EXISTS proposal_id uuid';
  END IF;

  IF to_regclass('public.proposal_templates') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.proposal_templates ADD COLUMN IF NOT EXISTS name text';
  END IF;
END $$;
